// Generated by scripts/compile-clienthello-presets.py; do not edit.
use std::{fmt, str::FromStr};
/// Pinned uTLS aa6edf4b11af82e110eea845bb2983d30138d651 profiles.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum ClientHelloProfile {
    Chrome83,
    Chrome87,
    Chrome96,
    Chrome100,
    Chrome102,
    Chrome106,
    Chrome120,
    Chrome131,
    Chrome133,
    Firefox99,
    Firefox102,
    Firefox105,
    Firefox120,
    Firefox148,
    Ios13,
    Ios14,
    Edge85,
    Edge106,
    Safari160,
    Safari263,
    Browser360110,
    Qq111,
    Chrome70,
    Chrome72,
    Firefox63,
    Firefox65,
    /// Legacy Zero alias; the upstream never defined Edge 120.
    Edge120,
    Random,
    Randomized,
    RandomizedNoAlpn,
}
impl ClientHelloProfile {
    pub const DEFAULT: Self = Self::Chrome133;
    pub const VERSIONED: &'static [Self] = &[
        Self::Chrome83,
        Self::Chrome87,
        Self::Chrome96,
        Self::Chrome100,
        Self::Chrome102,
        Self::Chrome106,
        Self::Chrome120,
        Self::Chrome131,
        Self::Chrome133,
        Self::Firefox99,
        Self::Firefox102,
        Self::Firefox105,
        Self::Firefox120,
        Self::Firefox148,
        Self::Ios13,
        Self::Ios14,
        Self::Edge85,
        Self::Edge106,
        Self::Safari160,
        Self::Safari263,
        Self::Browser360110,
        Self::Qq111,
        Self::Chrome70,
        Self::Chrome72,
        Self::Firefox63,
        Self::Firefox65,
    ];
    pub fn canonical_name(self) -> &'static str {
        match self {
            Self::Chrome83 => "chrome-83",
            Self::Chrome87 => "chrome-87",
            Self::Chrome96 => "chrome-96",
            Self::Chrome100 => "chrome-100",
            Self::Chrome102 => "chrome-102",
            Self::Chrome106 => "chrome-106",
            Self::Chrome120 => "chrome-120",
            Self::Chrome131 => "chrome-131",
            Self::Chrome133 => "chrome-133",
            Self::Firefox99 => "firefox-99",
            Self::Firefox102 => "firefox-102",
            Self::Firefox105 => "firefox-105",
            Self::Firefox120 => "firefox-120",
            Self::Firefox148 => "firefox-148",
            Self::Ios13 => "ios-13",
            Self::Ios14 => "ios-14",
            Self::Edge85 => "edge-85",
            Self::Edge106 => "edge-106",
            Self::Safari160 => "safari-16.0",
            Self::Safari263 => "safari-26.3",
            Self::Browser360110 => "360-11.0",
            Self::Qq111 => "qq-11.1",
            Self::Chrome70 => "chrome-70",
            Self::Chrome72 => "chrome-72",
            Self::Firefox63 => "firefox-63",
            Self::Firefox65 => "firefox-65",
            Self::Edge120 => "edge-120",
            Self::Random => "random",
            Self::Randomized => "randomized",
            Self::RandomizedNoAlpn => "randomizednoalpn",
        }
    }
    pub fn alpn_protocols(self) -> &'static [&'static str] {
        if self == Self::RandomizedNoAlpn {
            &[]
        } else if matches!(self, Self::Firefox102) {
            &["h2"]
        } else {
            &["h2", "http/1.1"]
        }
    }
    /// Negotiable TLS 1.3 suites; the wire preset also retains upstream legacy suites.
    pub fn cipher_suites(self) -> &'static [u16] {
        match self {
            Self::Firefox63
            | Self::Firefox65
            | Self::Firefox99
            | Self::Firefox102
            | Self::Firefox105
            | Self::Firefox120
            | Self::Firefox148 => &[0x1301, 0x1303, 0x1302],
            Self::Safari263 => &[0x1302, 0x1303, 0x1301],
            _ => &[0x1301, 0x1302, 0x1303],
        }
    }
}
impl Default for ClientHelloProfile {
    fn default() -> Self {
        Self::DEFAULT
    }
}
impl fmt::Display for ClientHelloProfile {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.canonical_name())
    }
}
impl FromStr for ClientHelloProfile {
    type Err = String;
    fn from_str(value: &str) -> Result<Self, String> {
        let name = value.trim().to_ascii_lowercase();
        let alias = match name.as_str() {
            "chrome" | "hellochrome_auto" => Some(Self::Chrome133),
            "firefox" | "hellofirefox_auto" => Some(Self::Firefox148),
            "safari" | "hellosafari_auto" => Some(Self::Safari263),
            "ios" | "helloios_auto" => Some(Self::Ios14),
            "edge" | "helloedge_auto" => Some(Self::Edge85),
            "qq" | "helloqq_auto" => Some(Self::Qq111),
            "safari-16" => Some(Self::Safari160),
            "edge-120" => Some(Self::Edge120),
            "random" => Some(Self::Random),
            "randomized" | "hellorandomized" | "hellorandomizedalpn" => Some(Self::Randomized),
            "randomizednoalpn" | "randomized-no-alpn" | "hellorandomizednoalpn" => {
                Some(Self::RandomizedNoAlpn)
            }
            _ => None,
        };
        if let Some(p) = alias {
            return Ok(p);
        }
        let normalized = name
            .strip_prefix("hello")
            .unwrap_or(&name)
            .replace("_shuffle", "")
            .replacen('_', "-", 1)
            .replace('_', ".");
        Self::VERSIONED.iter().copied().find(|p| p.canonical_name() == normalized).ok_or_else(|| format!("unsupported client fingerprint `{value}`; select a versioned TLS 1.3 browser preset, random, randomized or randomizednoalpn"))
    }
}
#[cfg(feature = "runtime")]
mod catalog;
#[cfg(feature = "runtime")]
pub mod key_share;
#[cfg(feature = "runtime")]
pub mod wire;
#[cfg(feature = "runtime")]
struct Preset {
    wire: &'static [u8],
    padding: bool,
    shuffle: bool,
    ech_lengths: &'static [u16],
    ech_ciphers: &'static [(u16, u16)],
}
impl ClientHelloProfile {
    /// Exact Xray v26.3.27 ModernFingerprints random-selection set.
    pub const RANDOM_CANDIDATES: &'static [Self] = &[
        Self::Firefox99,
        Self::Firefox102,
        Self::Firefox105,
        Self::Firefox120,
        Self::Chrome83,
        Self::Chrome87,
        Self::Chrome96,
        Self::Chrome100,
        Self::Chrome102,
        Self::Chrome106,
        Self::Chrome120,
        Self::Chrome131,
        Self::Ios13,
        Self::Ios14,
        Self::Edge85,
        Self::Edge106,
        Self::Safari160,
        Self::Browser360110,
        Self::Qq111,
    ];
}
#[cfg(feature = "runtime")]
mod randomized;
